version: 2.1

jobs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - store_artifacts:
          path: ./TDDCalculate.js
          destination: artifact-file
orbs:
  node: circleci/node@3.0.0

workflows:
  test_my_app:
    jobs:
      - test
      
jobs:
  build:
    working_directory: /tmp
    steps:
      
