version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  save-artifacts:
    steps:
      - checkout
      - store_artifacts:
          path: ./TDDCalculate.js
          destination: artifact-file

workflows:
  node-tests:
    jobs:
      - node/test
      - save-artifacts
      
      
